### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by nutszebra** [onnx/onnx-coreml#346] opened 2018-10-17 07:31 UTC
When I use `convert` in onnx-coreml, segmentation fault arises.
My codes are:
```python
import sys
from onnx import onnx_pb
from onnx_coreml import convert
model_in = sys.argv[1]
model_out = sys.argv[2]
model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
coreml_model = convert(model_proto, preprocessing_args={'image_scale': 1 / 255.}, image_input_names=['0'], image_output_names=['258'], deprocessing_args={'image_scale': 255.})
coreml_model.save(model_out)
```
Are there any ideas to avoid segmentation fault?

My environment is like this:
```
python (3.5.2)
Click (7.0)
numpy (1.15.2)
onnx (1.3.0)
onnx-coreml (0.3.0)
```

**Comment by aseemw** [comment] 2018-10-17 15:16
Do you get an error message? 

Please provide more information to reproduce the issue.

**Comment by nutszebra** [comment] 2018-10-18 06:16
Error messages are  like this:
```
$ python convert_onnx_to_coreml.py  /home/nutszebra/Downloads/prizma/gogh_e_2/gogh_e_2.onnx /home/nutszebra/Downloads/test.mlmodel
Segmentation fault (core dumped)
```

My pip list:
```
asn1crypto (0.22.0)
backcall (0.1.0)
cffi (1.10.0)
Click (7.0)
conda (4.5.11)
ConnPlotter (0.7a0)
coremltools (2.0)
cryptography (1.8.1)
decorator (4.3.0)
idna (2.6)
ipython (6.5.0)
ipython-genutils (0.2.0)
jedi (0.12.1)
mkl-fft (1.0.6)
mkl-random (1.0.1)
numpy (1.15.2)
onnx (1.3.0)
onnx-coreml (0.3.0)
packaging (16.8)
parso (0.3.1)
pexpect (4.6.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
protobuf (3.6.1)
ptyprocess (0.6.0)
pycosat (0.6.3)
pycparser (2.18)
pycrypto (2.6.1)
Pygments (2.2.0)
PyNEST (2.8.0)
pyOpenSSL (17.0.0)
pyparsing (2.2.0)
PyYAML (3.11)
requests (2.14.2)
ruamel-yaml (-VERSION)
setuptools (40.4.3)
simplegeneric (0.8.1)
six (1.11.0)
Topology (2.8.0)
traitlets (4.3.2)
typing (3.6.6)
typing-extensions (3.6.6)
wcwidth (0.1.7)
wheel (0.29.0)
```

My environments:
```
Ubuntu 14.04 LTS
Python 3.5.2
miniconda3-4.1.11
```

**Comment by aseemw** [comment] 2018-10-18 15:15
Not sure what's causing it. 
Hard to say without looking at the model and reproducing the issue.

**Comment by nutszebra** [comment] 2018-10-22 05:49
I uncommented ` mlmodel = MLModel(builder.spec) `, but still segmentation fault arises at `onnx-coreml==0.3.0`.
I find that `onnx-coreml==0.1.1` works properly without segmentation fault.

**Comment by h-shib** [comment] 2018-10-22 06:07
I have same error as above.  
I tried https://github.com/onnx/onnx-coreml/issues/346#issuecomment-431247960 solution and nothing changed.  

I also tried same onnx => mlmodel conversion script on my Mac environment, but the result was the same.  

I think this problem comes from `Upsample` operator, since other onnx model which has exactly the same architecture except `Upsample` could convert correctly.

**Comment by aseemw** [comment] 2018-10-22 15:33
@nutszebra Does the error occur with a many onnx models or with a particular model? 
Which Mac version do you have? 

I have not come across this behavior. It would be great if you can provide a a tiny model that reproduces the issue. 

@h-shib I believe we have tests running with upsample layer. I'll double check.

**Comment by h-shib** [comment] 2018-10-23 00:17
@aseemw thanks for your reply.  
I'll share the both ONNX files. `base.onnx` is able to convert to `base.mlmodel`, but `base+upsample.onnx` isn't.  
Could you check those?  

https://www.dropbox.com/sh/loieailoyjtxujw/AACv9h_47yLCdH_H02u1IJxia?dl=0

**Comment by aseemw** [comment] 2018-10-23 00:35
Okay, it seems the `base+upsample.onnx` model causes a crash at https://github.com/onnx/onnx-coreml/blob/53d7c434037d23f28f48f23abf50d6574477d917/onnx_coreml/_shapeinference.py#L8

which is the shape inference code for onnx. @smessmer any idea on what could be causing this? 

@h-shib My suggestion would be to open an issue on the [onnx repo](https://github.com/onnx/onnx) since the crash is related to the shape inference method in onnx.

**Comment by h-shib** [comment] 2018-10-23 00:41
@aseemw thank you for quick reply.  
OK, I'll open an issue on ONNX repo and will share the result on this issue.

**Comment by yuvdar** [comment] 2018-10-23 13:49
hey, I had the same issue, and fix it. you can see the fix in a PR I just opened.  https://github.com/onnx/onnx-coreml/pull/349

**Comment by aseemw** [comment] 2018-10-23 20:19
@h-shib PR #349 is merged, can you check again, after building from top of master,  if your issue is resolved ?

**Comment by h-shib** [comment] 2018-10-24 00:45
My problem was solved. Thank you so much! @aseemw @yuvdar

**Closed** 2018-10-24 01:06 UTC
