### ISSUE TITLE
Developments on slicing

### ISSUE THREAD

**Issue by jbmaxwell** [onnx/onnx-coreml#321] opened 2018-06-23 18:55 UTC
Is there any timeline on extending slicing support? I'm getting this error (converting a PyTorch UNet):

> TypeError: Error while converting op of type: Slice. Error message: Only single axis Slice is supported now

and I really don't know how I could get around it.

**Comment by cbecker** [comment] 2018-07-18 09:34
I am using multidimensional slicing so it seems to be working.

However I had to tweak it as it was slicing on the wrong dimension. I think this is because CoreML assumes we have `[channels, height, width]`, while in my case it is `[batch_size, channels, height_width]`

I had to change `_operators.py`, at `_convert_slice` to have the following:
```
    if len(axes) == 1:
        if axes[0] == 1:
            axis = 'channel'
        elif axes[0] == 2:
            axis = 'height'
        elif axes[0] == 3:
            axis = 'width'
        else:
            return err.unsupported_op_configuration(builder, node, graph, "Slice is supported only along H, W or C dimensions")
```
(before it was `channel -> 0`, `height -> 1`, `width -> 2`)

Any ideas on why this was like this before?

**Comment by aseemw** [comment] 2018-07-18 15:43
CHW is the default order of tensors in CoreML and several layers depend on this order. 
Since, as of now, the converter does not interpret the meaning of each dimension for each tensor for the whole graph jointly, it does not recognize new cases (such as [B,C,H] in this case).

**Comment by jbmaxwell** [comment] 2018-07-20 18:45
hmm... the error I'm getting above is from the previous check, at the top of _operators.py: 
    ```
if len(axes) != 1:
        return err.unsupported_op_configuration(builder, node, graph, "Only single axis Slice is supported now")
```
Anyway, I tried your fix, but unsurprisingly I get the same error.

**Comment by cbecker** [comment] 2018-07-26 07:52
@aseemw I understand that. Still it's quite limiting, would it make sense to take dimension ordering as a parameter to the convert function? Right now it's in an unusable state for anyone working on images from pytorch.

@jbmaxwell As a workaround you can generate two concatenated slicing operations, one working on a dimension at a time. I think this is how pytorch is doing is, as I can export to onnx -> coreml easily.

**Comment by jbmaxwell** [comment] 2018-07-26 15:00
Well, I upgraded last night and my error changed. Now I'm seeing:
 ```onnx_coreml/_operators.py in _convert_pool(builder, node, graph, err)
    229         pad_t = pads[0]
    230         pad_l = pads[1]
--> 231         pad_b = pads[2]
    232         pad_r = pads[3]
    233 

IndexError: list index out of range```
Really not sure why, but looking into it...

**Comment by aseemw** [comment] 2018-07-26 21:15
Yes I agree dimension ordering is a pain and the converter currently does not handle it properly when the actual order varies from the defaults that are hard coded.

One WIP item that will help in this regard is the native shape inference in ONNX that went in recently (PR #323). The converter needs to be updated to take into account the shape information now available. 

The ideal case is if the converter can reason about the shapes internally without the input from the user. But in some cases, as pointed out, it could be useful to take additional inputs from the user on dim ordering. We will look into that. 

@cbecker you mentioned the input is of the type `[Batch, channel, height/width]` that leads to issues. What are the kind of models that use that kind of flat image inputs? 
In particular, it would be useful if you can provide some of the code snippets which error out during conversion. They would definitely help in making test cases while more logic is added to the converter to handle different shapes.

**Comment by jbmaxwell** [comment] 2018-07-27 19:20
@cbecker: I have to confess that I'm new to python/numpy and not sure exactly what you mean by "generate (two) concatenated slicing operations". Are you suggesting separating out slices for each dimension? The slice that (I think) is causing the problems is of the form `[: , : , i:j , x:y]`. I tried something like:
```
slice1 = input[: , : , i:j , :]
slice2 = slice1[: , : , : , x:y]
```
which (I believe) will produce the same output, but it gives me the same error.
The model I'm trying to convert is this pytorch tiramisu: https://github.com/bfortuner/pytorch_tiramisu

**Comment by cbecker** [comment] 2018-07-27 20:39
@jbmaxwell which pytorch version are you using? I am using pytorch and using the above code to convert a u-net-like network to coreml and I had no issues. Can you post a snippet with a minimal working version to reproduce the error you're getting?

**Comment by jbmaxwell** [comment] 2018-07-27 20:50
I'm on pytorch 0.3.1. I tried updating but it produces all kinds of errors in the model. I do pytorch to onnx: 
```
import torch
from torch.autograd import Variable
import torch.onnx

dummy_input = Variable(torch.randn(1, 3, 88, 128).cuda())
torch.onnx.export(model, dummy_input, 'UNet.onnx')
```
then onnx to coreml:

```
import torch
import onnx
from onnx_coreml import convert

model = onnx.load('UNet.onnx')
coreml_model = convert(
    model,
    image_input_names=['instrument_highlight_piano_roll'],
    image_output_names=['instrument_articulated_piano_roll'],
)
coreml_model.save('UNet.mlmodel')
```
The error is: ```TypeError: Error while converting op of type: Slice. Error message: Only single axis Slice is supported now```

**Comment by cbecker** [comment] 2018-07-27 20:56
I am using 0.4.0 or 0.4.1, that may be the issue. I'd suggest that you upgrade to 0.4.0, what errors are you getting? It may be that 0.3.x was using a single slice op for both dimensions and 0.4.x is using two, which is why it works then with coreml.

Another option is to modify the onnx file and split the slicing op into two, though that's more involved.

**Comment by jbmaxwell** [comment] 2018-07-27 21:09
Right, okay. I've upgraded again to 0.4, and this is the current error: 
```
/pytorch_tiramisu/utils/training.py in error(preds, targets)
     52     incorrect = preds.ne(targets).cpu().sum()
     53     err = incorrect/n_pixels
---> 54     return round(err,5)
     55 
     56 def train(model, trn_loader, optimizer, criterion, epoch):

TypeError: type Tensor doesn't define __round__ method
```
Confusing... I don't understand why it seems to be looking for Tensor.round() not just Python's round() function(??)

**Comment by jbmaxwell** [comment] 2018-07-27 22:41
Okay, I was able to run an epoch, but now the jupyter kernel just restarts when I try to convert from onnx to coreml. Very strange. Presumably something is crashing ungracefully somewhere.

**Comment by cbecker** [comment] 2018-07-27 22:49
This is more of a pytorch question. I think it's because you're forgetting to convert to numpy here. Try
```
incorrect = preds.ne(targets).cpu().numpy().sum()
```

**Comment by jbmaxwell** [comment] 2018-07-27 22:53
Do you mean that this might affect the onnx model? I only ask because with err.item() it runs an epoch without issue (and with reasonable results, given it's only 1 epoch).

**Comment by cbecker** [comment] 2018-07-27 23:05
> Do you mean that this might affect the onnx model? 
The pytorch version probably does, as the onnx exporter is part of pytorch AFAIK.

**Comment by jbmaxwell** [comment] 2018-07-27 23:08
yeah, it seems like my env is a bit pooched now. Turns out even just the ```import torch``` was restarting the kernel.

**Comment by jbmaxwell** [comment] 2018-07-28 02:31
Okay, some progress. I had to apply your axes patch from above, but I also have a problem in concat:
```
TypeError: Error while converting op of type: Concat. Error message: Unsupported axis 1 in input of shape
```

**Comment by cbecker** [comment] 2018-07-28 08:46
@jbmaxwell I'd recommend that you post this somewhere else and ping me. Can you post it in an online notebook? then i can have a look and we don't add too many messages to this thread

**Comment by jbmaxwell** [comment] 2018-07-28 13:32
I got it to complete by changing the default `mode` in `_convert_concat` from `None` to `'CONCAT'`. While that seems like a reasonable guess, it's very possible this will just be incorrect. I'll look into posting a notebook for you to look at; that would be super helpful.

**Comment by cbecker** [comment] 2018-07-30 11:51
> @cbecker you mentioned the input is of the type [Batch, channel, height/width] that leads to issues. What are the kind of models that use that kind of flat image inputs?
In particular, it would be useful if you can provide some of the code snippets which error out during conversion. They would definitely help in making test cases while more logic is added to the converter to handle different shapes.

@aseemw The input type that leads to problems is `[batch, channel, height, width]` when the input tensor is 4D, which is the common format when dealing with images in pytorch. Whenever we have a slicing operation on a 4D tensor with this format it will fail, which means that it's pretty much unusable (at least from what I see) with pytorch if using images.

**Comment by aseemw** [comment] 2018-07-30 15:58
@cbecker That is surprising, since the converter code is supposed to be written assuming this very format, [BCHW]. 
Maybe there is a bug in the converter code. 
Can you please provide a small code snippet with image and slicing operations, to reproduce the error, so that we can debug. Thanks.

**Comment by cbecker** [comment] 2018-07-30 16:05
Sure, you can try this:
```
import torch
import torch.onnx as tonnx
import torch.nn as nn
from torch.autograd import Variable

class MyModel(nn.Module):
    def forward(self, x):
        return x[:, :, :, 1:-1]

dummy_input = Variable(torch.randn(1, 3, 224, 224))
model = MyModel()

tonnx.export(model, dummy_input, "/tmp/model.onnx", verbose=True)

from onnx_coreml import convert


mlmodel = convert("/tmp/model.onnx")
```
[model.onnx.zip](https://github.com/onnx/onnx-coreml/files/2241956/model.onnx.zip)


And the onnx file is attached if you don't have pytorch, you can run the last two lines only then.

**Comment by jbmaxwell** [comment] 2018-08-09 21:15
@cbecker: It seemed like a got a little farther with this, but it was a false alarm. I've posted a question here (https://stackoverflow.com/questions/51605747/errors-converting-pytorch-unet-tiramisu-into-coreml-via-onnx), but nothing so far.

**Comment by aseemw** [comment] 2018-08-24 00:44
PR #328 should handle the single axis slice op when the input tensor is 4-D (BCHW)

**Comment by cbecker** [comment] 2018-08-24 08:05
Thanks Assem. I'll give it a try when it's merged. Now we're using a custom patch here to make it work.

**Comment by aseemw** [comment] 2018-09-29 19:35
Other slice cases are also covered in PR #341

**Closed by aseemw** 2018-09-29 19:35 UTC
Labels: enhancement
